In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
iris = load_iris()

In [87]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [ ]:
'''

HERE I AM COMPARING DIFFERENT MODELS USING CROSS VALIDATION

'''

In [88]:
logreg_scores = cross_val_score(LogisticRegression(max_iter=150), iris.data, iris.target, cv=skf)
logreg_scores

array([1.  , 0.94, 0.96])

In [89]:
np.average(logreg_scores)

np.float64(0.9666666666666667)

In [90]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target,cv=skf)
svm_scores

array([1.  , 0.94, 0.96])

In [91]:
np.average(svm_scores)

np.float64(0.9666666666666667)

In [92]:
tree_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=skf)
tree_scores

array([1.  , 0.92, 0.94])

In [93]:
np.average(tree_scores)

np.float64(0.9533333333333333)

In [94]:
forest_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target,cv=skf)
forest_scores

array([1.  , 0.94, 0.92])

In [95]:
np.average(forest_scores)


np.float64(0.9533333333333333)

In [64]:
'''

USING CROSS VALIDATION FOR HYPERPARAMETER TUNING

'''

'\n\nUSING CROSS VALIDATION FOR HYPERPARAMETER TUNING\n\n'

In [65]:
'''
1. SVM
'''

'\n1. SVM\n'

In [66]:
svm_scores = cross_val_score(SVC(C=1.0), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [67]:
svm_scores = cross_val_score(SVC(C=0.1), iris.data, iris.target)
svm_scores

array([0.9       , 0.93333333, 0.9       , 0.96666667, 0.9       ])

In [68]:
svm_scores = cross_val_score(SVC(C=0.01), iris.data, iris.target)
svm_scores

array([0.9       , 0.93333333, 0.9       , 0.96666667, 0.93333333])

In [69]:
'''
2. LOGISTIC REGRESSION
'''

'\n2. LOGISTIC REGRESSION\n'

In [70]:
logreg_scores = cross_val_score(LogisticRegression(C=1.0, max_iter=150), iris.data, iris.target)
logreg_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [71]:
logreg_scores = cross_val_score(LogisticRegression(C=10.0, max_iter=150), iris.data, iris.target)
logreg_scores

array([0.96666667, 1.        , 0.96666667, 0.93333333, 1.        ])

In [72]:
logreg_scores = cross_val_score(LogisticRegression(C=0.01, max_iter=150), iris.data, iris.target)
logreg_scores

array([0.76666667, 0.93333333, 0.76666667, 0.9       , 0.93333333])

In [73]:
'''
3. DECISION TREE
'''

'\n3. DECISION TREE\n'

In [74]:
tree_scores = cross_val_score(DecisionTreeClassifier(max_depth=10), iris.data, iris.target)
tree_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [75]:
tree_scores = cross_val_score(DecisionTreeClassifier(max_depth=1), iris.data, iris.target)
tree_scores

array([0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [76]:
tree_scores = cross_val_score(DecisionTreeClassifier(max_depth=5), iris.data, iris.target)
tree_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [81]:
'''
4. RANDOM FOREST
'''

'\n4. RANDOM FOREST\n'

In [78]:
forest_scores = cross_val_score(RandomForestClassifier(n_estimators=100), iris.data, iris.target)
forest_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [79]:
forest_scores = cross_val_score(RandomForestClassifier(n_estimators=20), iris.data, iris.target)
forest_scores

array([0.96666667, 0.96666667, 0.9       , 0.9       , 1.        ])

In [80]:
forest_scores = cross_val_score(RandomForestClassifier(n_estimators=3), iris.data, iris.target)
forest_scores

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])