In [10]:
# Functions	     Descriptions
# array()	        : creates a matrix
# dot()	        : performs matrix multiplication
# transpose()     : transposes a matrix
# linalg.inv()	: calculates the inverse of a matrix
# linalg.det()	: calculates the determinant of a matrix
# flatten()	    : transforms a matrix into 1D array


In [9]:
import numpy as np


arr = np.array([[1, 3], [4, 5]])


arr.dtype
arr.shape
arr.ndim

2

In [1]:
#array(matrix)

import numpy
array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

#note: you can create matrix of any size with any elements.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#dot()

import numpy
array = numpy.array([[1,1,1],[1,1,1],[1,1,1]])

array2 = numpy.array([[2,2,2],[2,2,2],[2,2,2]])

array3 = numpy.array([[3,3,3],[3,3,3],[3,3,3]])

result_of_matrix_multiplication = numpy.dot(array3,array2,array)

print(result_of_matrix_multiplication)


#note: you can multiply any 2 or more matrixes, and matrix multiplication follows the Commutative Property of Multiplication.
# note: you can multiply matrixes like [ 1*2 and 2*3 , as long as colomn of 1st matrix and row of second matrix are same you can multiply it.] , -by your's truely.

[[18 18 18]
 [18 18 18]
 [18 18 18]]


In [3]:
# transpose() 


import numpy
matrix = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

transposed_matrix = numpy.transpose(matrix)
print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
# linalg.inv()	: calculates the inverse of a matrix

import numpy
array2 = numpy.array([[3,1,2],[7,12,22],[52,13,41]])

inverse_matrix = numpy.linalg.inv(array2)
print(inverse_matrix)

#note: make sure it not a singular matrix (determinant should not be zero)

[[ 0.50366748 -0.03667482 -0.00488998]
 [ 2.09535452  0.04645477 -0.12713936]
 [-1.30317848  0.03178484  0.07090465]]


In [5]:
# linalg.det()

import numpy
array2 = numpy.array([[3,1,2],[7,12,22],[52,13,41]])

determinant_of_matrix = numpy.linalg.det(array2)
print(determinant_of_matrix)

409.00000000000017


In [7]:
# flatten()	

import numpy
array2 = numpy.array([[3,1,2],[7,12,22],[52,13,41]])

flattened_matrix = array2.flatten()
print(flattened_matrix)

#note: it's array_name.flatten() not numpy.flatten(array_name)

[ 3  1  2  7 12 22 52 13 41]
