In [10]:
# Functions	     Descriptions
# array()	        : creates a matrix
# dot()	        : performs matrix multiplication
# transpose()     : transposes a matrix
# linalg.inv()	: calculates the inverse of a matrix
# linalg.det()	: calculates the determinant of a matrix
# flatten()	    : transforms a matrix into 1D array


In [9]:
import numpy as np


arr = np.array([[1, 3], [4, 5]])


arr.dtype
arr.shape
arr.ndim

2

In [ ]:
import numpy as np

# create a 2x2 matrix
matrix1 = np.array([[1, 3], 
                   [5, 7]])

print("2x2 Matrix:\n",matrix1)

# create a 3x3  matrix
matrix2 = np.array([[2, 3, 5],
             	    [7, 14, 21],
                    [1, 3, 5]])
                    
print("\n3x3 Matrix:\n",matrix2)

In [4]:
import numpy as np

# create two matrices
matrix1 = np.array([[1, 3]]
             		)
             
matrix2 = np.array([[2, 6, 8], 
                    [4, 8, 10]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

# note: you can multiply matrixes like [ 1*2 and 2*3 , as long as colomn of 1st matrix and row of second matrix are same you can multiply it.] , -by your's truely.

matrix1 x matrix2: 
 [[14 30 38]]


In [8]:
import numpy as np

# create a matrix
matrix1 = np.array([[2, 6, 8], 
                    [4, 8, 10]])

# get transpose of matrix1
result = np.transpose(matrix1)

print(result)

[[ 2  4]
 [ 6  8]
 [ 8 10]]


In [11]:
import numpy as np

# create a 3x3 square matrix
matrix1 = np.array([[1, 3, 5], 
             		[7, 9, 2],
                    [4, 6, 8]])

# find inverse of matrix1
result = np.linalg.inv(matrix1)

print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


In [12]:
import numpy as np

# create a matrix
matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 1],
                    [2, 3, 4]])

# find determinant of matrix1
result = np.linalg.det(matrix1)

print(result)

-5.000000000000001


In [13]:
import numpy as np

# create a 2x3 matrix
matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 7]])

result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 7]
